#!/usr/bin/env bash
# Script that will display information about subdomains

# Function to retrieve DNS information for a subdomain
DNS_info() {
    local ANSWER
    ANSWER=$(dig "$2" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
    echo "The subdomain $1 is a $(echo "$ANSWER" | awk '{print $4}') record and points to $(echo "$ANSWER" | awk '{print $5}')"
}

# Main script logic
if [[ $# == 1 ]]; then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for subdomain in "${subdomains[@]}"; do
        CONCAT="$subdomain.$1"
        DNS_info "$subdomain" "$CONCAT"
    done
else
    CONCAT="$2.$1"
    DNS_info "$2" "$CONCAT"
fi
