#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

# Backup configuration files
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Set a user in the config by replacing '#user' and its value
/bin/sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Replace port 80 with 8080 in the sites-available config
/bin/sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

# Check if Nginx is running and stop it if it is
if pgrep nginx > /dev/null; then
    service nginx stop
fi

# Start Nginx with the new nginx user
service nginx start
